version: "2"

services:

  backend:
    build: ./backend
    command: npm start
    environment:
      NODE_ENV: development
    networks:
      - backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/usr/src/backend:rw

  selenium:
    image: selenium/standalone-chrome-debug
    networks:
      - backend
    ports:
      - "4444:4444"

  owasp_zap:
    image: owasp/zap2docker-stable
    networks:
      - backend
    ports:
      - "8080:8080"
    command: zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.key=0123456789 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config scanner.strength=INSANE

networks:
  backend:
    driver: bridge
